//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tocsoft.DateTimeAbstractions.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tocsoft.DateTimeAbstractions.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime static properties are not testable.
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not call {0}.{1} as they are not testable, use an abstraction instead..
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime static properties are not testable.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not call {0}.{1} as they are not testable, use an abstraction instead..
        /// </summary>
        internal static string ClockTimerAnalyzer_InvocationMessageFormat {
            get {
                return ResourceManager.GetString("ClockTimerAnalyzer_InvocationMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not call {0}.{1} as they are not testable, use an abstraction like the available {2} class instead..
        /// </summary>
        internal static string ClockTimerAnalyzer_InvocationMessageFormat_DirectToClockTimer {
            get {
                return ResourceManager.GetString("ClockTimerAnalyzer_InvocationMessageFormat_DirectToClockTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopwatch is not testable.
        /// </summary>
        internal static string ClockTimerAnalyzerDescription {
            get {
                return ResourceManager.GetString("ClockTimerAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopwatch is not testable.
        /// </summary>
        internal static string ClockTimerTitle {
            get {
                return ResourceManager.GetString("ClockTimerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use {0} as it is not testable, use an abstraction instead..
        /// </summary>
        internal static string ClockTimerTypeAnalyzer_ReferenceMessageFormat {
            get {
                return ResourceManager.GetString("ClockTimerTypeAnalyzer_ReferenceMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use {0} as it is not testable, use an abstraction like the available {1} class instead..
        /// </summary>
        internal static string ClockTimerTypeAnalyzer_ReferenceMessageFormat_DirectToClockTimer {
            get {
                return ResourceManager.GetString("ClockTimerTypeAnalyzer_ReferenceMessageFormat_DirectToClockTimer", resourceCulture);
            }
        }
    }
}
